apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sdgcandiate-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.apps.appdev-6.pd.stonedoor.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sdgcandiate
spec:
  hosts:
  - "*.apps.appdev-6.pd.stonedoor.io"
  gateways:
  - sdgcandiate-gateway
  http:
  - match:
    - uri:
        prefix: /v1/api/sdg/demo/candidate
