apiVersion: v1
kind: BuildConfig
metadata:
  name: stonelabdocker
  namespace: labdemo-dev
  labels:
    app: stonelabdocker
    name: stonelabdocker
spec:
  output:
    to:
      kind: DockerImage
      name: stonelabdocker:latest
  resources: {}
  source:
    type: Git
    git:
      ref: master
      uri: https://github.com/zhejingl/stonedoorlabe
  strategy:
     type: Docker
     dockerStrategy: {}